{% set name = "inja" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pantor/inja/archive/v{{ version }}.tar.gz
  sha256: e628d994762dcdaa9a97f63a9b8b73d9af51af0ffa5acea6bdbba0aceaf8ee25

build:
  number: 0

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - nlohmann_json >=3.8.0
  run:
    - nlohmann_json >=3.8.0

test:
  commands:
    - test -d ${PREFIX}/include/inja  # [unix]
    - test -f ${PREFIX}/include/inja/inja.hpp  # [unix]
    - test -f ${PREFIX}/include/inja/renderer.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/inja/injaConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/inja/injaConfigVersion.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/inja/injaTargets.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\inja\inja.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\inja\renderer.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\injaConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\injaConfigVersion.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\injaTargets.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/pantor/inja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Template Engine for Modern C++
  description: |
    Inja is a template engine for modern C++, loosely inspired by jinja for python.
    It has an easy and yet powerful template syntax with all variables, loops,
    conditions, includes, callbacks, and comments you need, nested and combined
    as you like.
  doc_url: https://pantor.github.io/inja/
  dev_url: https://github.com/pantor/inja

extra:
  recipe-maintainers:
    - andrewannex
    - jessemapel
    - scsides
    - kberryUSGS
